# Generated by Django 4.2.7 on 2023-12-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_documento_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel')], default='pdf', max_length=10),
        ),
    ]
