# Generated by Django 4.2.7 on 2023-12-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_documento_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo_documento',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word'), ('excel', 'Excel')], max_length=10),
        ),
    ]
