version: 1
services:
  - name: web
    buildCommand: python -m pip install -r requirements.txt
    command: "daphne -u /tmp/daphne.sock myportfolio.asgi:application"
    env:
      - key: DJANGO_SECRET_KEY
        generate: true
    
    middleware:
  - uvicorn.middleware.UvicornH11ClientDisconnect
  